### ISSUE TITLE
Mangled edge properties on  p2-pdb:

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#16]
Edge:

![image](https://user-images.githubusercontent.com/112839/85280251-adec1d00-b47f-11ea-960f-ed879b5d14ff.png)

In kb-p2:

```json
{
  "iri": "http://purl.obolibrary.org/obo/RO_0002026",
  "filename": "5302336_R__2",
  "label": "in_register_with",
  "type": "Related",
  "short_form": "RO_0002026"
}
```

In pdb-p2:

```json
{
  "typ": [
    "5302336_R__2"
  ],
  "filename": [
    "RO_0002026"
  ],
  "catmaid_server": [
    "http://purl.obolibrary.org/obo/RO_0002026"
  ],
  "type": [
    "in_register_with"
  ],
  "short_form": "Related"
}
```

**Comment by matentzn** [comment]
Note to self: on triplestore level this is correct:

http://ts.p2.virtualflybrain.org/rdf4j-workbench/repositories/vfb/explore?resource=_%3Anode1ebf12vkcx2595369

So it must be on import (CSV level?)
