### ISSUE TITLE
Import does not preserve types of annotation values

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/neo4j2owl#24]
when importing annotations from an ontology, correctly typed as say "Boolean", they are imported as strings. The problem lies in the last rows of the `extractIndividualAnnotations` function.

**Comment by matentzn** [comment]
Actually, this still works on a property by property basis..

**Comment by matentzn** [comment]
Rule:

- if in config, use that (warn if there is a non-boolean)
- if all values are true/false turn it to boolean (configurable)
- if 95% are true/false, turn to boolean and warn/error (pipeline should fail)

**Comment by matentzn** [comment]
apoc.convert.toBoolean(value)

**Comment by matentzn** [comment]
https://neo4j-contrib.github.io/neo4j-apoc-procedures/index33.html#_normalize_boolean_properties

**Comment by matentzn** [comment]
The way this happens now:



1) If the datatype is hard-coded in the config like:

2) If the datatype is not hard-coded, a cast is attempted. There is a new setting now:

```
relation_type_threshold: 0.95
```

If 95% of all values of a property are of a type, that type is coerced. Note that this could go wrong, as neo will fail hard if an illegal value is coerced.

3) If that fails as well, String type is used. (and an explanation printed in the log!)

**Comment by dosumis** [comment]
- [ ] TODO - review/edit CURIES @dosumis
