### ISSUE TITLE
Extend default indexing on Neo instances to include short_form on :Class & :Individual

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#28]
Configuration should allow specification of additional :labels to generate indexes on short_form for.

This is required for effective testing of pdb queries.

**Comment by matentzn** [comment]
Since I do not need `short_form` for ingest (I only ever use IRI, such as in):

```
MERGE (n:Entity { iri: cl.iri }) ...
```

I would suggest to add the two indexes right after PDB is first loaded up. I will do that now, and we can discuss it on the PR.

**Comment by matentzn** [comment]
For posterity, you can add index in this pipeline step:

https://github.com/VirtualFlyBrain/vfb-pipeline-update-prod/blob/0aea5b1e7a6a7486c66cf7a82837cf4de149aa9f/process.sh#L30
