### ISSUE TITLE
Multiple annotations on axioms are collapsed to single

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/neo4j2owl#30]
Multiple axiom annotations are collapsed to single currently, so if we have, for example, two xrefs on a relation, only one gets translated.

**Comment by dosumis** [comment]
What examples should I review?

Looks OK when these come from KB

![image](https://user-images.githubusercontent.com/112839/86914048-8bacfd00-c117-11ea-891b-f214f9b5ad41.png)

**Comment by matentzn** [comment]
Ah i don’t know one top of my head, it only should up in my local tests.. it only happens if you have two values for one property on a relation, say two voxels or type labels.. I don’t know wether there are such cases in VFB?
