### ISSUE TITLE
Typing - (lists of) ints and floats become (lists of) strings

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#31]
kp.p2:
![image](https://user-images.githubusercontent.com/112839/86456623-41dca500-bd1a-11ea-8554-046ff1ba9093.png)

pdb.p2
![image](https://user-images.githubusercontent.com/112839/86403970-a231ff00-bca6-11ea-9e70-ca7aa5ddd666.png)

**Comment by matentzn** [comment]
```
MATCH p=()-[r:in_register_with]->() where exists (r.index) RETURN r.index LIMIT 25
```

in kb.p2 yields this for me:

![image](https://user-images.githubusercontent.com/7070631/86435553-e6ee8200-bd08-11ea-8f5c-fbd0a9a4d385.png)


Are you sure that you tried kb?

For pdb I actually worked on datatyping last week - there are some problems with the dynamic typing at the moment, but maybe the datatyping issue is solved now.

**Comment by matentzn** [comment]
In fact, this reveals something else: in KB, if some neo property is not assigned to valid annotation property, its not changed from a single value to a list.. This does not matter for anything downstream, as the exporter will still export this information, just noticing it here..

**Comment by dosumis** [comment]
> Are you sure that you tried kb?

Sorry - pasto.  Corrected above.

**Comment by dosumis** [comment]
>   in KB, if some neo property is not assigned to valid annotation property, its not changed from a single value to a list.

Can we automatically make all a list (apart from label, short_form and iri) as part of kb -> kb2 ? 

Changing in KB is possible, but will cause some extra work/co-ordination.  Would be much easier if we can deal with these changes in one go  - on dedicated branches & servers for pipeline 2.

**Comment by matentzn** [comment]
Should work now, test a bit, for example:

```
MATCH (n) WHERE EXISTS(n.voxel) RETURN DISTINCT "node" as entity, n.voxel AS voxel LIMIT 25 UNION ALL MATCH ()-[r]-() WHERE EXISTS(r.voxel) RETURN DISTINCT "relationship" AS entity, r.voxel AS voxel LIMIT 25
```

**Comment by dosumis** [comment]
Looks good.
