### ISSUE TITLE
Using "label" in KB.

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/neo4j2owl#36]
The problem. We treat "label" as built-in vocabulary in the neo4j2owl converter to allow it to be single string-valued in PDB and enforce it where an rdfs:label does not exist. Changing that is complicated, because built-in vocabulary (like `iri`, `label`, `short_form`) works very different from the normal annotations. Because of that we currently cannot use `label` as the property key for labels that should be exported. There are three ways to deal with the issue:

1. `label` is renamed to `label_rdfs`, but otherwise kept as a single valued (not array-type) property. That way, the pipeline know to export it correctly. This is the current solution and does not need any further work from my end.
2. The KB->OWL step gets a small preprocessing phase (which it does right now) that renames label to label_rdfs before the export pipeline is run. The advantage is: maybe 30 min of work for me. Disadvantage, the KB export step is not 100% minimal. I prefer this option because (a) your code continues to work and (b) since the KB I work of is a throw-away product, there is no risk of this approach leading to an undesired database state. 
3. We add a configuration option to the exporter that allows mapping of built-in properties to existing properties. I estimate this to be about 6 hours of work, because the exporter, right now, actually does not have any configuration options at all (only the importer). The advantage of the approach is that no additional pipeline processing steps are required. The disadvantage is that we need to maintain an additional config option, and we invest 6 hours better spend elsewhere.

**Comment by dosumis** [comment]
Related issues: 
https://github.com/VirtualFlyBrain/vfb-pipeline-kb2kb/issues/4 
https://github.com/VirtualFlyBrain/VFB_neo4j/issues/202

**Comment by matentzn** [comment]
@dosumis you commented midway through the comment; the options are now laid out! Happy voting!

**Comment by dosumis** [comment]
I think option1 is best, but we should add an *import* config step that allows resolution to be specified where a term has multiple labels.

**Comment by matentzn** [comment]
Maybe the correct way to handle this is to ensure labels are unique in the shape validation step; configuring this would be really messy - like adding literally the preferred label of a class into a id->label map in the config file. That way you have total control over which labels you want to drop, ingest etc, in the usual ROBOT way. Or am I misunderstanding something?

**Comment by matentzn** [comment]
@dosumis and I reviewed this today in a meeting and it all looks fine.
