### ISSUE TITLE
Include preferred roots in PDB

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#37]
It would be very useful to have preferred roots tagged in pdb.  Unfortunately, this not currently present - presumably due this being recorded as an annotation axiom on the ontology.  

![image](https://user-images.githubusercontent.com/112839/88794964-25a41a80-d197-11ea-89b8-b09e42aa58c4.png)

Perhaps too much of a stretch to get this in - but very useful for removing abstract classes from graph/tree views.

**Comment by matentzn** [comment]
Can you explain this a bit more? What is a preferred root?

**Comment by matentzn** [comment]
Ah now I see

**Comment by matentzn** [comment]
Hmmm interesting I will try what I can do. Maybe this is actually easy, however adding that to the importer is a bit of overkill. Let me think about it though.

**Comment by matentzn** [comment]
The pipeline now generated `nodeLabel` annotations for all preferred root terms, which will result in all those nodes getting a neo4j node label `preferred_root`.
