### ISSUE TITLE
Synonyms inconsistently represented as JSON

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#38]
For synonyms and definitions, I thought we’d agreed that all values should be JSON, whether or not the axioms are annotated.  Looks like, for synonyms at least, only those with annotations are represented as JSON, e.g.:
![image](https://user-images.githubusercontent.com/112839/88913349-a24afd80-d258-11ea-8158-a2933261aa3e.png)

```cql
MATCH (n:Anatomy:Class) WHERE EXISTS(n.has_exact_synonym) 
RETURN  n.label, n.short_form, n.has_exact_synonym ORDER BY n.label limit 10
```

![image](https://user-images.githubusercontent.com/112839/88914057-f0143580-d259-11ea-93ae-425625717882.png)

The current solution is hard to process: have to check wether string is valid JSON before deciding whether to process.

IIRC - the APs for which axion annotations & values should be represented in JSON are specified here:

https://github.com/VirtualFlyBrain/vfb-prod/blob/master/neo4j2owl-config.yaml#L9

It strikes me that we chose a rather obscure name for this config `obo_assumption_overwrite_defaults:`

I don't think there's anything particularly OBO-ish about this. 

How about `represent_values_and_annotations_as_json` ?

(Fixing is high priority as this is a requirement for producing valid VFB_json for geppetto.)

**Comment by matentzn** [comment]
The only obo thing about this (you invented that name at some point) was that it looks at synonyms by the default, not at arbitrary annotation properties.. But I will rename it.

**Comment by matentzn** [comment]
This is fixed in `pdbl`.

**Comment by dosumis** [comment]
Center has multiple values (x,y, co-ords).  These are correctly represented as a list.

![image](https://user-images.githubusercontent.com/112839/89167311-2829ba00-d573-11ea-9e2d-04b223b12dcc.png)
