### ISSUE TITLE
pdb load failure on part_of - possible due to edge property typing issue?

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#45]
https://jenkins.virtualflybrain.org/view/pip_pipeline2/job/pip_vfb-prod/375/console

> LOAD CSV WITH HEADERS FROM "file:/relationship_part_of.txt" AS cl
> MATCH (s:Entity { iri: cl.start}),(e:Entity { iri: cl.end})
> MERGE (s)-[r:part_of]->(e) SET r.iri = cl.iri SET r.short_form = cl.short_form SET r.label = cl.label SET r.type = cl.type - {} - {}
> ERROR: An error has occurred.. 22318.93 sec
> java.util.concurrent.ExecutionException: org.neo4j.graphdb.QueryExecutionException: Property values can only be of primitive types or arrays thereof

**Comment by dosumis** [comment]
Oddly - the cypher doesn't set any unusual types.  The only properties on part_of edges in the KB are:


["short_form", "label", "type", "iri"]
["label", "iri", "short_form"]

**Comment by dosumis** [comment]
But there do seem to be some missing part_of edges:

pdb: 216,451
kb: 270,037

(@Robbie1977 - could this be a sync issue?)

**Comment by matentzn** [comment]
@dosumis as the error did not occur during the last run, can we rename the issue to investigate why there are 50K less part of edges in PDB than KB? That seems really wrong!

**Comment by dosumis** [comment]
OK.  Weird that the error just disappeared.  Leave the numbers issue with me.  It may represent unreleased data.

**Comment by dosumis** [comment]
Looks like difference is due to this unreleased dataset:

"TrumanWood2018" | 24368

Closing - we can re-open if bug re-appears.
