### ISSUE TITLE
OWL to Neo4J annotations on annotations

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/neo4j2owl#8]
This is underspecified right now.

e.g. 
<img width="607" alt="image" src="https://user-images.githubusercontent.com/112839/65318747-2262fa00-db96-11e9-80df-10a124652b99.png">

becomes flattened and merged with the values of the same AP directly annotating the Class.

{"database_cross_reference_oio": [
    "FlyBase:FBrf0141667",
    "FlyBase:FBrf0194268",
    "FlyBase:FBrf0221438",
    "FlyBase:FBrf0146917",
    "FlyBase:FBrf0220443",
    "VFB:FBbt_00067346",
    "FlyBase:FBrf0205814",
    "FlyBase:FBrf0221412"
  ]
...}

I.e. - the association with definition is lost.

We have various ad-hoc methods for dealing with this in the current pdb.  
OLS uses JSON strings.  PDB expands xrefs on synonyms and defs into (AP) edges to Individuals using CURIE expansions.  Rules for how to do this for various xrefs (direct vs annotations on annotations)  are implicit in code.   

We need a generic spec for dealing with annotations on annotations, but for this ticket I'm going to concentrate on a solution for database_cross_reference_oio annotations on annotations, via CURIE expansions:

1. Conversion references a standard config for CURIE expansions to generate Individual iris In this case 

"FlyBase": "http://flybase.org/reports/"

=> (i:Individidual ( { iri: "http://flybase.org/reports/"FBrf0141667" })

2. We then need a spec for the edge, taking into account that we may  need to preserve 1:many for each AP:value pair.  Maybe:

(c:Class)-[:database_cross_reference_oio { definition_iao: 'Ipsum Lorem', annotation_on: "definition_iao"}]-(i:Individidual ( { iri: "http://flybase.org/reports/"FBrf0141667" })

This is involves denomalisation, but  is close to the current spec and would work nicely for  synonyms - where we can have  multiple synonyms, each with references. The annotation_on property allows for additional annotation on these edges while recording what annotation is being annotated in OWL.

**Comment by dosumis** [comment]
Note: This deviates from current VFB neo schema in that we substitute the xrefs AP for a specific publication one in the case of def xrefs to FlyBase.  I think we can handle the change though.

**Comment by dosumis** [comment]
Solution: literal value is always on node.  If AP annotated with an xref, it appears on the edge too.

**Comment by matentzn** [comment]
Lets close this in favour of https://github.com/VirtualFlyBrain/neo4j2owl/issues/12
