### ISSUE TITLE
Allow for custom mapping file of neo4j property to iri

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/neo4j2owl#9]
```
- property_mapping: 
   label: 
       iri: http://www.w3.org/2000/01/rdf-schema#label
```

()-[label:]-()
({label:...})

- https://github.com/VirtualFlyBrain/VFB_neo4j/pull/173/files

**Comment by matentzn** [comment]
Check this file:  src/uk/ac/ebi/vfb/neo4j/data_sig_vfb.csv

**Comment by dosumis** [comment]
Too much on this sheet.

Divide job into 2:

For now - focus on APs & OPs needed for KB.  This is constrained to what's used in the schema. High priority.  Keep as table.  3 columns: safe_label, iri,  type, ontology source for label.

Aim - run simple checks: 
1. safe_label_uniqueness
2. Check whether tracks source label and report if not.




For PDB - It may be better to have  a check at load time for any clashing  labels, and a config that resolves these.

**Comment by dosumis** [comment]
Reports

edge types in KB (some cleaning needed)

``` 
MATCH ()-[r]->() with r 
OPTIONAL MATCH (p:Property { iri: r.iri }) 
return distinct r.short_form, r.label, r.iri, p.short_form, p.label
```

r.short_form	r.label	r.iri	p.short_form	p.label
"source"	"has_source"	"http://purl.org/dc/terms/source"	"source"	"has_source"
"references"	null	"http://purl.org/dc/terms/references"	"references"	"has_reference"
null	null	null	null	null
"RO_0002113"	"has_presynaptic_terminals_in"	"http://purl.obolibrary.org/obo/RO_0002113"	"RO_0002113"	"has_presynaptic_terminals_in"
"RO_0002110"	"has postsynaptic terminal in"	"http://purl.obolibrary.org/obo/RO_0002110"	"RO_0002110"	"has postsynaptic terminal in"
"RO_0002131"	"overlaps"	"http://purl.obolibrary.org/obo/RO_0002131"	"RO_0002131"	"overlaps"
"RO_0002110"	"has_postsynaptic_terminal_in"	"http://purl.obolibrary.org/obo/RO_0002110"	"RO_0002110"	"has postsynaptic terminal in"
"BFO_0000050"	"part of"	"http://purl.obolibrary.org/obo/BFO_0000050"	"BFO_0000050"	"part_of"
"RO_0002101"	"fasciculates_with"	"http://purl.obolibrary.org/obo/RO_0002101"	"RO_0002101"	"fasciculates_with"
"RO_0002100"	"has_soma_location"	"http://purl.obolibrary.org/obo/RO_0002100"	"RO_0002100"	"has_soma_location"
"BFO_0000050"	"part_of"	"http://purl.obolibrary.org/obo/BFO_0000050"	"BFO_0000050"	"part_of"
"RO_0002202"	"develops_from"	"http://purl.obolibrary.org/obo/RO_0002202"	"RO_0002202"	"develops_from"
"OBI_0000312"	"is_specified_output_of"	"http://purl.obolibrary.org/obo/OBI_0000312"	"OBI_0000312"	"is_specified_output_of"
"RO_0002292"	"expresses"	"http://purl.obolibrary.org/obo/RO_0002292"	"RO_0002292"	"expresses"
"RO_0002351"	"has_member"	"http://purl.obolibrary.org/obo/RO_0002351"	"RO_0002351"	"has_member"
"depicts"	"depicts"	"http://xmlns.com/foaf/0.1/depicts"	"depicts"	"depicts"
"C888C3DB-AEFA-447F-BD4C-858DFE33DBE7"	"has_exemplar"	"http://purl.obolibrary.org/obo/C888C3DB-AEFA-447F-BD4C-858DFE33DBE7"	"C888C3DB-AEFA-447F-BD4C-858DFE33DBE7"	"has_exemplar"
"c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0"	"exemplar_of"	"http://purl.obolibrary.org/obo/c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0"	"c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0"	"exemplar_of"
"RO_0002350"	"member_of"	"http://purl.obolibrary.org/obo/RO_0002350"	"RO_0002350"	"member_of"
"license"	"has_license"	"http://purl.org/dc/terms/license"	"license"	"has_license"
"license"	null	"http://purl.org/dc/terms/license"	"license"	"has_license"
"hasDbXref"	null	"http://www.geneontology.org/formats/oboInOwl#hasDbXref"	"hasDbXref"	"database_cross_reference"
"VFBext_0000003"	"has_signal_channel"	"http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000003"	"VFBext_0000003"	"has_signal_channel"
"VFBext_0000002"	"has_background_channel"	"http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000002"	"VFBext_0000002"	"has_background_channel"
"RO_0002026"	"in_register_with"	"http://purl.obolibrary.org/obo/RO_0002026"	"RO_0002026"	"in_register_with"
null	"in register with"	"http://purl.obolibrary.org/obo/RO_0002026"	null	null
"RO_0002026"	"JFRC2_template_mask130819"	"http://purl.obolibrary.org/obo/RO_0002026"	"RO_0002026"	"in_register_with"
"RO_0002026"	"Ito Half Brain"	"http://purl.obolibrary.org/obo/RO_0002026"	"RO_0002026"	"in_register_with"
"VFBext_0000008"	"has hemidriver"	"http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000008"	"VFBext_0000008"	"has hemidriver"
"hasDbXref"	"database_cross_reference"	"http://www.geneontology.org/formats/oboInOwl#hasDbXref"	"hasDbXref"	"database_cross_reference"
"references"	"has_reference"	"http://purl.org/dc/terms/references"	"references"	"has_reference"

List or node/edge properties:

...

**Comment by dosumis** [comment]
Set of edge properties in use in KB is v.small:

http://purl.obolibrary.org/obo/BFO_0000050
http://purl.obolibrary.org/obo/C888C3DB-AEFA-447F-BD4C-858DFE33DBE7
http://purl.obolibrary.org/obo/OBI_0000312
http://purl.obolibrary.org/obo/RO_0002026
http://purl.obolibrary.org/obo/RO_0002100
http://purl.obolibrary.org/obo/RO_0002101
http://purl.obolibrary.org/obo/RO_0002110
http://purl.obolibrary.org/obo/RO_0002113
http://purl.obolibrary.org/obo/RO_0002131
http://purl.obolibrary.org/obo/RO_0002202
http://purl.obolibrary.org/obo/RO_0002292
http://purl.obolibrary.org/obo/RO_0002350
http://purl.obolibrary.org/obo/RO_0002351
http://purl.obolibrary.org/obo/c099d9d6-4ef3-11e3-9da7-b1ad5291e0b0
http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000002
http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000003
http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000008
http://purl.org/dc/terms/license
http://purl.org/dc/terms/references
http://purl.org/dc/terms/source
http://www.geneontology.org/formats/oboInOwl#hasDbXref
http://xmlns.com/foaf/0.1/depicts

**Comment by dosumis** [comment]
Properties on nodes -> APs

proporties with mappings to OWL iri:

```
iri
short_form
```

OBO tag mappings:

We only use these: 

```
comment -> rdfs
label -> rdfs
definition -> IAO
xrefs -> OboInOwl
synonyms -> OboInOwl?
is_obsolete
```

(But should allow the complete OboInOWL set)

potentially problematic:

```
synonym
synonyms
```

There is, unfortunately, no single AP mapping that groups all synonym subtypes.

Anything else we should treat as local to VFB (TBD: how to turn these into IRIs) 

We should probably  keep a white-list of these to avoid duplication due to typos etc.  Here's a list of what we have:

```
DOI
FlyBase
License_note
PMID
accession
bespoke
catmaid_annotation_id
catmaid_annotations
catmaid_datasets
catmaid_name
catmaid_neuron_id
catmaid_paper_id
catmaid_server
catmaid_skeleton_ids
catmaid_type
center
cubic_micrometer_overlap
data_link_pre
dataset_link
dataset_spec_text
description
do_not_publish
downstream
extent
facts
filename
folder
homepage
id_in_source
index
infer_overlap
iri
label
license_logo
license_summary_url
license_url
link_base
link_icon_url
link_postfix
logo
logo_url
miniref
name
nrrd
obj
ontology_name
orientation
post
pre
prefix
production
properties
property
pseudonyms
pub
public
schema
self_xref
swc
test
thumbnail
title
typ
type
upstream
voxel
voxel_overlap_center
voxel_overlap_left
voxel_overlap_right
wlz
xref_db
year
```

**Comment by dosumis** [comment]
New plan: Curated set of properties (in OWL?) for kb & pdb = master set for whole pipeline.  Properties are only loaded from here to kb (not from any other ontology).

Robot pipeline for loading integration layer - only takes axioms referencing properties in KB.
